# Generated by Django 2.1.5 on 2019-01-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_auto_20190124_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='current_big_pizzap_rice',
            new_name='current_big_pizza_price',
        ),
    ]
