# Generated by Django 2.1.5 on 2019-01-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_pizzachoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzachoice',
            name='client_ip',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
