# Generated by Django 2.1.5 on 2019-02-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0007_pizzachoice_client_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzachoice',
            name='equation',
            field=models.CharField(max_length=100),
        ),
    ]
